version: '3.1'

services:
  appliances:
    build: ./appliances
    container_name: appliances
    ports:
      - 8081:3000
    volumes:
      - ./appliances/src:/home/app/src
    command: npm run start
    environment:
      - APP_PORT=3000
    env_file:
      - .env
    depends_on:
      - auth

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:8080
    links:
      - appliances
      - auth
    depends_on:
      - auth
      - appliances

  auth:
    build: ./auth
    container_name: auth
    ports:
      - 8082:3001
    volumes:
      - ./auth/src:/home/app/src
    command: npm run start
    environment:
      - APP_PORT=3001
    env_file:
      - .env